### ISSUE TITLE
[Request] Awesome Flutter Event

### ISSUE THREAD

**Issue by karx** [karx/FlutterArsenal#15]
link:  https://www.meetup.com/Dataioticshub/events/262026385/   
tag: meetup       
excerpt:  great event to network  
date: 10-10-20      
email-id:  gmail@muemail.com 
teaser:

**Comment by karx** [comment]
Thank you @karx for submitting a new battle ground for the __FlutterArsenal__.
The Event at web link: [Event link](https://www.meetup.com/Dataioticshub/events/262026385/) on __10-10-20 is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @karx for event organization and ideas.

**Comment by karx** [comment]
Thank you @karx for submitting a new battle ground for the __FlutterArsenal__.
The Event at web link: [Event link](https://www.meetup.com/Dataioticshub/events/262026385/) on __10-10-20__ is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @karx for event organization and ideas.

**Comment by karx** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by flutter-arsenal** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
