### ISSUE TITLE
[Request] Lets see if this gets picked

### ISSUE THREAD

**Issue by karx** [karx/FlutterArsenal#17]
github: https://github.com/karx/FlutterArsenal    
tag:   kaaro     
excerpt:   this is a test on but a long one 
email-id:  karx@in.com 
teaser:    https://avatars2.githubusercontent.com/u/7826138?s=88&v=4

**Comment by flutter-arsenal** [comment]
Thank you @karx for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_karx/FlutterArsenal_](https://github.com/karx/FlutterArsenal) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @karx for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @karx your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @karx. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
